### ISSUE TITLE
User collision doesn't invalidate bedrock breaking

### ISSUE THREAD

**Issue by JonasStorm** [LXYan2333/Fabric-Bedrock-Miner#11]
A. User collision stops slime placement, other valid placements are not tried.
B. User collision stops piston placement, but the torch has already been placed. Torch isn't broken.

**Comment by JacktheDevel0per** [comment]
Hmmm ok.

**Comment by LXYan2333** [comment]
Fixed

**Comment by ToiletKun** [comment]
1.20 needed, plz!    orz
