### ISSUE TITLE
net.minecraft.block.PistonBlock and net.minecraft.item.Item are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader

### ISSUE THREAD

**Issue by bakaEC** [LXYan2333/Fabric-Bedrock-Miner#14]
求解，在拉取项目搭建运行后，在空手右击触发后会报错，请问有什么解决方法吗
java.lang.ClassCastException: class net.minecraft.block.PistonBlock cannot be cast to class net.minecraft.item.Item (net.minecraft.block.PistonBlock and net.minecraft.item.Item are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @1e4f4a5c)

在右击同时会有以下提示：
[Render thread/WARN] (FileUtil) Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
接下来会报以上的错，然后保存世界退出。

**Comment by bakaEC** [comment]
PS:我使用了main分支搭建了1.17.1版本，手动修改的两个json文件内版本，请问这样的搭建方式有误吗。

**Comment by bakaEC** [comment]
而且您的build.gradle中使用的依赖版本是1.17.1，fabric.mod.json里配置却是1.16.x，不修改的话也会报错呢qwq

**Comment by LXYan2333** [comment]
checkout到对应分支再构建吧，我不大会用git，现在main分支就是个烂摊子。

**Comment by bakaEC** [comment]
收到。非常感谢，不过目前您已经把1.17.1分支给关闭了，我试试去gitee上调取缓存吧。

**Comment by LXYan2333** [comment]
呃，git小白请教一下，关闭分支是什么操作？
我开隐私窗口下载1.17.1分支，没有任何问题啊。

**Comment by bakaEC** [comment]
很怪异，这边显示您的1.17.1的分支是close状态，昨天尝试了无法同步到您的分支，不过我通过gitee上未合并的分支已经部署完成了。
刚才再次尝试貌似可以使用。
