### ISSUE TITLE
1.18?

### ISSUE THREAD

**Issue by Dzovanio** [LXYan2333/Fabric-Bedrock-Miner#21]
Will there be an update to 1.18 version?

**Comment by JacktheDevel0per** [comment]
I guess, it would not be hard, most of the code is ids and just placing blocks and stuff so it's just weird mappings changes in yarn.

**Comment by mrGRINCH** [comment]
Please could we get this updated to 1.18?

**Comment by LXYan2333** [comment]
Will do in January, 2022.

**Comment by mrGRINCH** [comment]
Awesome, thank you!

**Comment by Bone0-0** [comment]
> 会在2022年1月完成。
Unable to hold oneself back

**Comment by Bone0-0** [comment]
> 会在2022年1月完成。
Unable to hold oneself back

**Comment by Bone0-0** [comment]
I can't help wanting it now，unable to hold oneself back！

**Comment by LXYan2333** [comment]
[https://github.com/LXYan2333/Fabric-Bedrock-Miner/releases/tag/1.18.1](https://github.com/LXYan2333/Fabric-Bedrock-Miner/releases/tag/1.18.1)
