### ISSUE TITLE
Mining Fails With all requirements met

### ISSUE THREAD

**Issue by SmallerDragons** [LXYan2333/Fabric-Bedrock-Miner#28]
I've tried using the latest version on my normal instance of Minecraft, and also tried using it on a completely new instance with only the one mod and fabric installed, and it still refuses to mine the bedrock

Haste II and an Efficiency V diamond or Netherite Pickaxe, I still receive the same message saying "Can't instantly mine piston! Efficiency V + Haste II required!

![image](https://user-images.githubusercontent.com/88168639/150658926-e9ee190b-66c3-4a11-9223-ec7f214350d3.png)

**Comment by JacktheDevel0per** [comment]
Hmm from this info Me and probably anyone else that would help can figure out, can you send all mod versions mc version fabric loader version and maybe logs? Also what software is the server running? Is it a singleplayer world?

**Comment by SmallerDragons** [comment]
The earlier images you saw was from a PaperMc Server, but it has worked there before.
![image](https://user-images.githubusercontent.com/88168639/150666462-51d535f8-a83c-4b05-858c-63f24caf6d81.png)
![image](https://user-images.githubusercontent.com/88168639/150666465-231e6a4f-2d53-4c33-9da0-bf5ef30863d4.png)

these are the mods I had installed before I drilled down till none were installed, before outright making a while new clean instance of Minecraft to try and recreate the failure
![image](https://user-images.githubusercontent.com/88168639/150666556-e21c155c-293f-4ff1-ba29-2cc123db6c29.png)
![image](https://user-images.githubusercontent.com/88168639/150666563-4678375c-d360-4f2b-ba7d-22ba49a5e64c.png
[latest.log](https://github.com/LXYan2333/Fabric-Bedrock-Miner/files/7919879/latest.log)
)

**Comment by LXYan2333** [comment]
I build a version that will show you the mining speed.

[bedrock-miner-for-1.18.1-debug.zip](https://github.com/LXYan2333/Fabric-Bedrock-Miner/files/7920087/bedrock-miner-for-1.18.1-debug.zip)

Please unzip it and replace the origin bedrock-miner mod, try again and send me the log.

**Comment by SmallerDragons** [comment]
[latest.log](https://github.com/LXYan2333/Fabric-Bedrock-Miner/files/7920736/latest.log)
Here is a log on the fully modded instance

**Comment by LXYan2333** [comment]
You installed a lot of mods. Please reproduce this bug with only this mod installed.

**Comment by SmallerDragons** [comment]
I understand. I will do some research and figure out which mod is causing the issue and report back here.

**Comment by SmallerDragons** [comment]
It seems like something on EMC-F-v2 has something, because after running a new instance with all original mods, it seems to prevent bedrock miner from working. EMC-F-v2-latest-1.18.1.jar supports Aristois a popular menu I used often. I can recreate the same issue although with a crash using various modules on other modified clients like Meteor client. However, I have figure it out so I will close with this comment. Thank you for your help!
