### ISSUE TITLE
1.17版本号错误

### ISSUE THREAD

**Issue by SunnySlopes** [LXYan2333/Fabric-Bedrock-Miner#3]
我在1.17中加入这个mod的1.17版本，显示需要1.16游戏
![image](https://user-images.githubusercontent.com/49802219/132119180-4bd84788-85de-4240-87f4-2b49834654b8.png)

**Comment by SunnySlopes** [comment]
改一下版本号就能用了

**Comment by LXYan2333** [comment]
更新了。
另外gitee上的好像没问题。
