### ISSUE TITLE
GAME CRASHED

### ISSUE THREAD

**Issue by vorsv** [LXYan2333/Fabric-Bedrock-Miner#31]
https://pastebin.com/PSA8Avpx
 IT CRASHES THE GAME DONT KNOW WHY

**Comment by LXYan2333** [comment]
try this [https://github.com/LXYan2333/Fabric-Bedrock-Miner/releases/download/1.18.1/bedrock-miner-1.0.0-for-minecraft-1.18.1.jar](https://github.com/LXYan2333/Fabric-Bedrock-Miner/releases/download/1.18.1/bedrock-miner-1.0.0-for-minecraft-1.18.1.jar)

**Comment by LXYan2333** [comment]
Wait, which version of Minecraft are you playing? I'm kinda confused.

**Comment by vorsv** [comment]
1.18.1

**Comment by vorsv** [comment]
trying this now 

> Wait, which version of Minecraft are you playing? I'm kinda confused.

**Comment by vorsv** [comment]
very cool thank you it worked
