### ISSUE TITLE
Doesn't work for 1.19

### ISSUE THREAD

**Issue by Notoriousi** [LXYan2333/Fabric-Bedrock-Miner#35]
The mod booting up works but right clicking any bedrock with this mod enabled will cause the client to crash

**Comment by LXYan2333** [comment]
[https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089](https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089)
