### ISSUE TITLE
希望能出1.19版

### ISSUE THREAD

**Issue by MouZ10** [LXYan2333/Fabric-Bedrock-Miner#36]
跪求1.19 ver

**Comment by IPCHIFUNG** [comment]
复议

**Comment by LXYan2333** [comment]
[https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089](https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089)

**Comment by Stioc98** [comment]
Can you please publish the jar file for us who can't get it?

**Comment by devjta** [comment]
Yeah, why is the link dead?

**Comment by df-f** [comment]
Any tip about how to making it working?

**Comment by python-longcheese** [comment]
求1.19版本！
