### ISSUE TITLE
Update for 1.19 (Previously given links don't work.)

### ISSUE THREAD

**Issue by sherbertdev** [LXYan2333/Fabric-Bedrock-Miner#41]
I know people have asked for this already, but as of now the links fail to take me anywhere but a 404.

**Comment by AngelFireLA** [comment]
https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089
or
https://github.com/LXYan2333/Fabric-Bedrock-Miner/actions/runs/2507441732
and click on artefacts

**Comment by SynergyDeveloper** [comment]
you cant click artefacts

**Comment by sherbertdev** [comment]
Thanks! It worked perfectly fine for me. 

@SynergyDeveloper If you still can't find the file, I attached the zip below.

[Artifacts.zip](https://github.com/LXYan2333/Fabric-Bedrock-Miner/files/9126092/Artifacts.zip)

**Comment by sherbertdev** [comment]
Thanks! It worked perfectly fine for me. 

@SynergyDeveloper If you still can't find the artifacts, I attached it below.

[Artifacts.zip](https://github.com/LXYan2333/Fabric-Bedrock-Miner/files/9126093/Artifacts.zip)
