### ISSUE TITLE
1.19

### ISSUE THREAD

**Issue by Clakorn** [LXYan2333/Fabric-Bedrock-Miner#42]
1.19 pls

**Comment by Notoriousi** [comment]
Download this: https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089

**Comment by JorisDek** [comment]
404

**Comment by JorisDek** [comment]
ooh need to sign in to github

**Comment by kuaiper** [comment]
thank you

**Comment by Iktsoi** [comment]
how to download NOOO

**Comment by kittenvr** [comment]
> Download this: https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089

Failed to generate URL to download artifact.

**Comment by FourFeaves** [comment]
> > Download this: https://github.com/LXYan2333/Fabric-Bedrock-Miner/suites/6957582944/artifacts/271525089
> 
> Failed to generate URL to download artifact.

+1

**Comment by 0Eshan7** [comment]
failed
