### ISSUE TITLE
1.19 no work mod (Bedrock miner), please help:(

### ISSUE THREAD

**Issue by Inzzzi** [LXYan2333/Fabric-Bedrock-Miner#45]
Hi, your mod doesn't work for me at 1.19. I tried everything, but nothing happened. I took a diamond pickaxe for efficiency 5 and made a beacon for haste 2, but nothing happened. Please help me:(((((

**Comment by Inzzzi** [comment]
HELP PLEASE!!!!!!

**Comment by JacktheDevel0per** [comment]
Did you enable the mod by clicking on bedrock? Does it ever send text?

**Comment by Inzzzi** [comment]
> 

he writes to me that there is no pickaxe for efficiency 5 or a beacon for haste 2

**Comment by Inzzzi** [comment]
![IMG_20220802_215948](https://user-images.githubusercontent.com/91669301/182432134-1dca74ff-0ce4-4b46-8267-737224e7b7c9.jpg)

**Comment by JacktheDevel0per** [comment]
are you sure you have eff 5 and haste 2?

**Comment by plutos-fungus** [comment]
I might also add, that running or jumping will give this message too

**Comment by LXYan2333** [comment]
[https://github.com/LXYan2333/Fabric-Bedrock-Miner/issues/28](https://github.com/LXYan2333/Fabric-Bedrock-Miner/issues/28)
please temporarily remove other mods and try again

**Comment by Inzzzi** [comment]
> 

 Yes

**Comment by Inzzzi** [comment]
> #28 please temporarily remove other mods and try again

I have only the fabric api installed in the mod folder and your mod

**Comment by Inzzzi** [comment]
thanks for the guys' help, I checked everything again and it worked!! The problem was in the beacon, I made it on haste 1 and not on 2:)

**Comment by Inzzzi** [comment]
thanks everyone
