### ISSUE TITLE
1.20.4支持

### ISSUE THREAD

**Issue by Adogs1** [LXYan2333/Fabric-Bedrock-Miner#80]
请添加对1.20.4支持

**Comment by devjta** [comment]
https://github.com/devjta/Fabric-Bedrock-Miner/releases

**Comment by Adogs1** [comment]
> https://githubfast.com/devjta/Fabric-Bedrock-Miner/releases

它会一直跟进更新？

**Comment by devjta** [comment]
Yeah, at least faster than LXYan. But there is also another one, who updates quite often and I think, the person also speaks mandarin: https://github.com/Bunnui/fabric-bedrock-miner

The source should be fine for 1.20.4.. Dont know, why there is no release.

**Comment by Adogs1** [comment]
> 是的，至少比 LXYan 快。但还有另一个人，他经常更新，我想，这个人也会说普通话：https://githubfast.com/Bunnui/fabric-bedrock-miner
> 
> 1.20.4 的源代码应该没问题。不知道，为什么没有发布。

I know him, but he can only use commands to modify and enable it. I still prefer you to keep updating the empty handed right click enable!

**Comment by Adogs1** [comment]
> > 是的，至少比 LXYan 快。但还有另一个人，他经常更新，我想，这个人也会说普通话：https://githubfast.com/Bunnui/fabric-bedrock-miner
> > 1.20.4 的源代码应该没问题。不知道，为什么没有发布。
> 
> 我认识他，但他只能使用命令来修改和启用它。我还是希望你继续更新空手右键启用！

我测试了他的，可以空手右键启用，他延缓破基岩的速度，使得很少出现幽灵方块，确实是个不错的选择
